### ISSUE TITLE
Invoke custom script when input is switched

### ISSUE THREAD

**Issue by xpufx** [feschber/lan-mouse#107]
Barrier has this parameter `--screen-change-script <path>` : `full path to script to run on screen change first argument is the new screen name` which runs a user defined script when input switching occurs.

I am using this feature to switch my monitor input with ddc commands as detailed here: https://xpufx.com/posts/hundred-percent-software-kvm-switch/

Is there similar functionality in lan-mouse?

**Comment by feschber** [comment]
Also: Are you aware of input-leap? It's the maintained barrier fork.

**Comment by feschber** [comment]
Will need to update for windows and update the documentation

**Comment by xpufx** [comment]
> Also: Are you aware of input-leap? It's the maintained barrier fork.

Somehow I missed this comment. At the time I posted the question none of the barrier forks had wayland support. Now input leap and the new synergy upstream Deskflow do seem to have it.

 Thank you for the enter hook support. Awesome. I will test it out asap.
