### ISSUE TITLE
Wheel scrolles too sensitive

### ISSUE THREAD

**Issue by ZhangSanMo** [feschber/lan-mouse#115]
# Platform
Windows 10
# Used Version
latest pre-release commitL: https://github.com/feschber/lan-mouse/commit/3e96b42067e7917b27e21c92ceedec681f8bd363
# Malfunction
client's mouse wheel scroll too sensitively. It just seems like that from top to bottom in one step.
# Expect
Mouse's wheel works like general action rather than "one-step".

**Comment by ZhangSanMo** [comment]
A very smart decision: using UDP.
Thanks a lot.

**Comment by feschber** [comment]
Yeah I need to implement value120 axis / high precision scroll events.

**Comment by MulverineX** [comment]
Too sensitive? My scroll wheel barely moves the page lol (latest dev build)

**Comment by ZhangSanMo** [comment]
> Too sensitive? My scroll wheel barely moves the page lol (latest dev build)

Yeah, it did not work as expect. As you say, barely moving the page.

**Comment by ZhangSanMo** [comment]
> Yeah I need to implement value120 axis / high precision scroll events.

It's a good news with reson found.

**Comment by feschber** [comment]
still having some trouble with the layer-shell and wlroots backends  that I need to figure out but libei and windows should now work better.

**Comment by xf-** [comment]
Scrolling worked before and with e21ab02 it goes nuts. Scrolls super sensitive from wayland to wayland - build on same commit. Reverting on server site and the issue is gone

**Comment by feschber** [comment]
Yes, I am aware of that. Will hopefully get to fix it tomorrow.

**Comment by ZhangSanMo** [comment]
problem still exists, both on touch pad and mouse wheel.

**Comment by MulverineX** [comment]
> Too sensitive? My scroll wheel barely moves the page lol (latest dev build)

This is fixed :)

**Comment by feschber** [comment]
> problem still exists, both on touch pad and mouse wheel.

can you test the latest main?

KDE Plasma is still giving me some trouble. On windows I fixed a bug that made scrolling to sensitive.

**Comment by ZhangSanMo** [comment]
> > problem still exists, both on touch pad and mouse wheel.
> 
> can you test the latest main?
> 
> KDE Plasma is still giving me some trouble. On windows I fixed a bug that made scrolling to sensitive.

It works fine, thanks for your attention.

I'll close this issue.

**Comment by feschber** [comment]
> > > problem still exists, both on touch pad and mouse wheel.
> > 
> > can you test the latest main?
> > 
> > KDE Plasma is still giving me some trouble. On windows I fixed a bug that made scrolling to sensitive.
> 
> It works fine, thanks for your attention.
> 
> I'll close this issue.

Thank you for reporting and testing!
