### ISSUE TITLE
Hyprland not working with 1px shell surface

### ISSUE THREAD

**Issue by Clutchnp** [feschber/lan-mouse#135]
[hyprlandCrashReport621782.txt](https://github.com/feschber/lan-mouse/files/15377432/hyprlandCrashReport621782.txt)

While capturing input if mouse is taken to the edge of the screen hyprland crashes 

```[2024-05-20T13:19:08Z WARN  lan_mouse::config] /home/clutch/.config/lan-mouse/config.toml: No such file or directory (os error 2)
[2024-05-20T13:19:08Z WARN  lan_mouse::config] Continuing without config file ...
[2024-05-20T13:19:08Z INFO  lan_mouse] release bind: [KeyLeftCtrl, KeyLeftShift, KeyLeftMeta, KeyLeftAlt]
[2024-05-20T13:19:08Z INFO  lan_mouse::capture_test] running input capture test
[2024-05-20T13:19:08Z INFO  lan_mouse::capture_test] creating input capture
[2024-05-20T13:19:08Z INFO  lan_mouse::capture] libei input capture not available: ZBus Error: org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.InputCapture” on object at path /org/freedesktop/portal/desktop
[2024-05-20T13:19:08Z INFO  lan_mouse::capture] using layer-shell input capture
[2024-05-20T13:19:08Z INFO  lan_mouse::capture_test] creating clients```

Thanks!

**Comment by feschber** [comment]
That's a Hyprland regression (something with the pointer constraints by the looks of things). Please report there and link the issue here. A crash should be easy to fix.

**Comment by Clutchnp** [comment]
Thanks for looking at I have made an issue at the Hyprland repo which can be tracked [here](https://github.com/hyprwm/Hyprland/issues/6170)

**Comment by ch4og** [comment]
I only see this behavior when using the stable version of Hyprland. There are no crashes when using the git version, but on git version I can't move the cursor if the other computer's location is set to [left] or [top], only [bottom] and [right] works. That's clearly a regression cause on hyprland 0.39.1 it works great

**Comment by Clutchnp** [comment]
This [solution](https://github.com/hyprwm/Hyprland/issues/6170#issuecomment-2124426896) tested and works

**Comment by feschber** [comment]
@Clutchnp has this been fixed upstream because you closed the issue?

**Comment by Clutchnp** [comment]
Oh mb i closed this by mistake

**Comment by feschber** [comment]
```diff
diff --git a/src/capture/wayland.rs b/src/capture/wayland.rs
index 9f2b82c..1aac930 100644
--- a/src/capture/wayland.rs
+++ b/src/capture/wayland.rs
@@ -146,8 +146,8 @@ impl Window {
         let g = &state.g;
 
         let (width, height) = match pos {
-            Position::Left | Position::Right => (1, size.1 as u32),
-            Position::Top | Position::Bottom => (size.0 as u32, 1),
+            Position::Left | Position::Right => (2, size.1 as u32),
+            Position::Top | Position::Bottom => (size.0 as u32, 2),
         };
         let mut file = tempfile::tempfile().unwrap();
         draw(&mut file, (width, height));
 ```
 
 Temporary workaround. I could upstream this but I'd rather get it fixed in Hyprland ...

**Comment by feschber** [comment]
You can use the patched [hyprland-fix branch](https://github.com/feschber/lan-mouse/tree/hyprland-fix) for now

**Comment by interbattles** [comment]
whats the difference between this and https://github.com/drendog/Hyprland/tree/fix/cursor-min-padding

**Comment by Clutchnp** [comment]
Waiting for [#6027](https://github.com/hyprwm/Hyprland/pull/6027) to be merged until then you can hyprland-fix-branch of lan-mouse

**Comment by Clutchnp** [comment]
With #6027 merged this should be resolved thanks everyone !!

**Comment by feschber** [comment]
Yes can confirm! Thanks everyone for your patience ;).
