### ISSUE TITLE
Mouse pointer can't return back to Hyprland's surface 

### ISSUE THREAD

**Issue by Clutchnp** [feschber/lan-mouse#138]
Related to [this issue](https://github.com/hyprwm/Hyprland/issues/6170#issuecomment-2123149334)

Using Hyprland(server) and i3(client) 

Mouse pointer once on i3's surface is locked to the surface and can't return back to Hyprland

**Comment by feschber** [comment]
This is #125

**Comment by Clutchnp** [comment]
mb and  thanks for looking , also I think it would be better to make this more clear in the readme to prevent further issues like these

**Comment by feschber** [comment]
> mb and  thanks for looking , also I think it would be better to make this more clear in the readme to prevent further issues like these

No worries! Will do
