### ISSUE TITLE
32-bit build fails

### ISSUE THREAD

**Issue by subhappy** [feschber/lan-mouse#141]
Hi, I've tried to compile lan-mouse both natively on the target i686-unknown-linux-gnu, and also crosscompiling from x86_64.
Both tries fail with the same error:

> error[E0308]: mismatched types
  --> /home/lars/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lan-mouse-0.8.0/src/frontend/gtk.rs:94:44
   |
94 |             let len = usize::from_be_bytes(len);
   |                       -------------------- ^^^ expected an array with a fixed size of 4 elements, found one with 8 elements
   |                       |
   |                       arguments to this function are incorrect
   |
note: associated function defined here
  --> /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/num/mod.rs:1256:5
   = note: this error originates in the macro `uint_impl` (in Nightly builds, run with -Z macro-backtrace for more info)
For more information about this error, try `rustc --explain E0308`.

**Comment by feschber** [comment]
this is an oversight. Thanks for reporting!

**Comment by subhappy** [comment]
Thanks for the software :)
