### ISSUE TITLE
KDE Request permission for input emulation cancelled immediately with no prompt

### ISSUE THREAD

**Issue by CupricReki** [feschber/lan-mouse#144]
Logs are filled with errors whenever starting lan-mouse. No prompt like before. Lan-mouse is not functional. Built using latest git.
```
lan_mouse::emulate::libei] requesting permission for input emulation
lan_mouse::emulate::libei] request cancelled!
```
Operating System: Arch Linux 
KDE Plasma Version: 6.0.5
KDE Frameworks Version: 6.3.0
Qt Version: 6.7.1
Kernel Version: 6.9.3-arch1-1 (64-bit)
Graphics Platform: Wayland

**Comment by feschber** [comment]
This can not really have anything to do with changes in lan-mouse. There must be something in KDE that remembered to not allow remote desktop permissions.

**Comment by CupricReki** [comment]
Well, I did another update and whatever the issue with KDE seems to be resolved.

**Comment by feschber** [comment]
If I had to guess, I would say it was probably something to do with the [persistence](https://invent.kde.org/network/kdeconnect-kde/-/merge_requests/639) feature
