### ISSUE TITLE
Keys stuck, when exiting through CTRL+ALT+SHIFT+WIN (Windows, Rdp, Libei?)

### ISSUE THREAD

**Issue by feschber** [feschber/lan-mouse#15]
When releasing the mouse from windows using the CTRL+ALT+SHIFT+WIN key combination, those keys get stuck, because a release key event is never sent to the windows client.

**Comment by ferdinandschober** [comment]
same issue on remote desktop portal backend (bug in KDE).

A workaround could be backend independent.

**Comment by feschber** [comment]
Same Problem with the RDP backend.

**Comment by MulverineX** [comment]
It appears that the windows key doesn't work at all on receiving clients, but I can't reproduce those other keys being "stuck", they continue to work just fine.

**Comment by feschber** [comment]
> It appears that the windows key doesn't work at all on receiving clients, but I can't reproduce those other keys being "stuck", they continue to work just fine.

It may not be immediately obvious but upon exiting the client, the keys remain in a pressed state until they are pressed and released again (either through the sending or receiving client). Thats what I mean by "stuck"
