### ISSUE TITLE
Where do I put the config.toml file in Windows?

### ISSUE THREAD

**Issue by EzequielBruni** [feschber/lan-mouse#171]
Starting the app automatically is actually fairly simple with shortcuts, but I don't know where the default location for the config.toml file should be. Would that be somewhere like `C:\Users\[user]\.config\lan-mouse\` maybe?

**Comment by EzequielBruni** [comment]
Never mind. I'm a dummy. I found the path in the command line.

**Comment by feschber** [comment]
To be fair I could have documented that better
