### ISSUE TITLE
Having issues scrolling with trackpad on hyprland

### ISSUE THREAD

**Issue by alokehpdev** [feschber/lan-mouse#172]
I have my pc and my laptop running hyprland. It used to work before but something seems to have messed it up. 
Works when running sway on same pc. Works with windows as well.
Is anyone else having similar issues? Looking for any pointers to solve this. Doesn't seem like package issue.
Only scrolls down and right. Even when I scroll left, scroll right happens. Even when I scroll up, scroll down happens.

**Comment by feschber** [comment]
Sounds like a Hyprland issue to me
