### ISSUE TITLE
How to stop `--test-capture`?

### ISSUE THREAD

**Issue by xf-** [feschber/lan-mouse#173]
I used a new tty, because I found no key that worked.

Tried a lot:
- `KeyLeftCtrl, KeyLeftShift, KeyLeftMeta, KeyLeftAlt`
- `ESC`
- `:q`
- `q`

**Comment by feschber** [comment]
ESC should release the cursor and then pressing CTRL+C in the terminal to stop the command.
(this wont work if capture is broken in some way)
Or if you have shell access you could run `killall lan-mouse`

**Comment by xf-** [comment]
I tried Ctrl+C as well and just got the capture information and no input worked.

Maybe it is related to https://github.com/feschber/lan-mouse/issues/174

If the input is emulated while test-capture is running, that would explain why I found no way to stop it.

**Comment by feschber** [comment]
I'm not sure #174 is related, since `--test-capture` does not emulate any input.
What system are you using here?

**Comment by xf-** [comment]
> I'm not sure #174 is related, since `--test-capture` does not emulate any input. What system are you using here?

Arch, plasma, wayland
