### ISSUE TITLE
cannot connect to my clients in windows when running it as daemon

### ISSUE THREAD

**Issue by godsplankh** [feschber/lan-mouse#180]
![image](https://github.com/user-attachments/assets/67fccdbe-84bd-41a1-959c-953555c1b57f)
by default the client states -> active shows false, for it to work i need toogle the connection by running the gui

**Comment by feschber** [comment]
See `activate_on_startup`: https://github.com/feschber/lan-mouse?tab=readme-ov-file#example-config

**Comment by godsplanhk** [comment]
yeah solved thanks
