### ISSUE TITLE
Issue with Hotkeys while controlling MacOS M1 

### ISSUE THREAD

**Issue by zhurai** [feschber/lan-mouse#198]
Hello, please let me know what needs to be provided (I am not daily driving this setup anymore as it was proving to be too disruptive while working - I had to return to X11 for now for Synergy)

- Main system (Mouse&Keyboard attached to): Linux Wayland (Sway)
- Connected system: MacOS M1

At first the hotkeys seem to work in MacOS M1 (for example using command/windows key + T to create a new tab)
However, after changing the state (I believe I released the keys back to the original/main system)

Restarting the lanmouse session on the Mac temporarily fixes the issue.

I don't have any hotkey issues when I used my main system to connect to a Linux box running X11.

**Comment by feschber** [comment]
One thing: Does pressing and releasing the keys individually get them working again?

**Comment by zhurai** [comment]
@feschber Sorry for the gap before answering (I didn't really want to boot into a temporary wayland setup during my work week)

- Pressing and releasing the keys individually does not get them working again
- The only thing that seems to fix it for me is disabling+enabling the connection on the MacOS client  (Irrelevant to linux client toggling of the session)
- The specific keys/hotkeys that I have found to consistently cause this issue is trying to change tabs by doing `ctrl+page_up/page_down`, shortly afterwards, the macos does not react to the windows key (command key) sent using the linux box's keyboard
- this creates a situation where if I try to open a tab to go to somewhere (`command+t`) this initially works, but after trying to change to another tab (`ctrl+page_up/page_down`) causes any `command+x` keybind to stop working

I'll send a trace from the mac box sometime later today - I'm rebooting back to x11 and cleaning up the log of PII and other irrelevant information.

---

Unrelated but still related to my usage - scrollwheel does not seem to work between wayland sway keyboard on MacOS, whereas works perfectly fine on the X11 box

**Comment by zhurai** [comment]
Trace logfile from the macos box: [lanmouse.log](https://github.com/user-attachments/files/17000311/lanmouse.log)

**Comment by Jacoby6000** [comment]
@zhurai does pressing the keys on the client device resolve the issue temporarily? I have a similar problem, most notably with caps-lock and the fn/globe modifier. I can press the respective key on the client device and that alleviates the problem up until it happens again.

**Comment by zhurai** [comment]
@Jacoby6000 Finally got around to testing on sway (since I was test driving KDE which helped with some other issues that might be more local/network based - for input-leap/synergy... but ran into some weird other issues there recently...) 

That suggestion does indeed help resolve the issue temporarily, though would be a bit too disruptive to use that as the workaround given how I use everything, but thanks!
