### ISSUE TITLE
Desktop file not installed when using as home manager module

### ISSUE THREAD

**Issue by istudyatuni** [feschber/lan-mouse#210]
Basically the title
```
dskw4hhk3fckpc6syh7k0lfkavd430kr-lan-mouse-0.9.1
└── bin
   └── lan-mouse
```
File exists (in cloned repo, I guess), but it's not linked anywhere
```
2zswckijabz0p5ym5anq69ai3iqs41k7-lan-mouse
├── build.rs
├── Cargo.lock
├── Cargo.toml
├── config.toml
├── de.feschber.LanMouse.desktop
├── de.feschber.LanMouse.yml
├── [...]
```

**Comment by feschber** [comment]
I'm not too familiar with NixOS but isn't homemanager responsible for config files rather than the package itself?
I think the desktop file should be installed via the package, however I'm not sure whether or not that is the case atm.
@PedroHLC @ICE-GB  can you comment on this?

**Comment by PedroHLC** [comment]
It needs a `xdg.desktopEntries.lan-mouse` around here: https://github.com/feschber/lan-mouse/blob/ab1b45ff45035ca566ccc12c4547994e03a13a1d/nix/hm-module.nix#L78

**Comment by ICE-GB** [comment]
Sorry, I have been using services. It should be fine now.
