### ISSUE TITLE
Weird timeout issues?

### ISSUE THREAD

**Issue by serdonke** [feschber/lan-mouse#213]
Been using `lan-mouse` for a while now, it worked flawlessly until today.

I have two systems setup, `left` and `right`

Both of them use Arch, KDE (Wayland) and are up to date.

Config for `left`
```toml
port = 4242
[right]
hostname = "donkinator"

activate_on_startup = true

ips = ["192.168.1.5"]
```

Config for `right`
```toml
port = 4242

[left]
hostname = "donkler"

ips = ["192.168.1.6"]

activate_on_startup = true

[right]

hostname = "donkinator"
```

`right` for some reason is `releasing-pointer` after few (2-3) seconds of inactivity, here is the systemd output, the issue is not reproduced on `left`, it works normally and the logs have no such warnings.

```
Oct 07 12:16:58 donkinator lan-mouse[1361]: [2024-10-07T06:46:58Z WARN  lan_mouse::server::ping_task] client not responding, releasing pointer!
Oct 07 12:17:01 donkinator lan-mouse[1361]: [2024-10-07T06:47:01Z WARN  lan_mouse::server::ping_task] client not responding, releasing pointer!
Oct 07 12:17:04 donkinator lan-mouse[1361]: [2024-10-07T06:47:04Z WARN  lan_mouse::server::ping_task] client not responding, releasing pointer!
Oct 07 12:17:08 donkinator lan-mouse[1361]: [2024-10-07T06:47:08Z WARN  lan_mouse::server::ping_task] client not responding, releasing pointer!
Oct 07 12:17:10 donkinator lan-mouse[1361]: [2024-10-07T06:47:10Z WARN  lan_mouse::server::ping_task] client not responding, releasing pointer!
Oct 07 12:17:10 donkinator lan-mouse[1361]: [2024-10-07T06:47:10Z WARN  lan_mouse::server::ping_task] client not responding, releasing pointer!
Oct 07 12:17:11 donkinator lan-mouse[1361]: [2024-10-07T06:47:11Z WARN  lan_mouse::server::ping_task] client not responding, releasing pointer!
Oct 07 12:17:12 donkinator lan-mouse[1361]: [2024-10-07T06:47:12Z WARN  lan_mouse::server::ping_task] client not responding, releasing pointer!
Oct 07 12:17:27 donkinator lan-mouse[1361]: [2024-10-07T06:47:27Z WARN  lan_mouse::server::ping_task] client not responding, releasing pointer!
Oct 07 12:17:32 donkinator lan-mouse[1361]: [2024-10-07T06:47:32Z WARN  lan_mouse::server::ping_task] client not responding, releasing pointer!
```

**Comment by feschber** [comment]
Have you changed anything about your system? Did you update lan-mouse?

And just to clarify: You mean when you control `left` (donkler) from `right` (donkinator) these messages appear and the pointer is released?

**Comment by serdonke** [comment]
@feschber 
1) Nothing that should matter I guess, I installed `xppenlinux` userspace drivers on `right` and removed them and tested things again, it did not matter.

I did change routers though, is there something specific that `lan-mouse` or one of the dependencies assume that I need to change in my router settings? I mean it does work just this time out issue.

Also `left` is a laptop and connected to the router via wifi and `right` uses Ethernet, I do not think that can be relevant, I did switch to wifi on `right` and had the same issue that I mentioned.

2) Using the latest stable release in the Arch `extra` repo on both systems which is `0.9.1-1`

3) Yes, controlling `left` with `right` does exactly that but when I control `right` with `left` there are no such issues for some reason, no warnings pop up in `left` systemd logs.

**Comment by feschber** [comment]
It does sound like some sort of network related issue. Wifi can be a bit tricky.

It would be helpful, if you could provide a tracelog from both sides.

To do so, run it via

```sh
LAN_MOUSE_LOG_LEVEL=trace lan-mouse 2>&1 | tee lan-mouse.log
```

then upload the `lan-mouse.log`.

Be sure to not enter any confidential information, as this will log all key strokes!

**Comment by serdonke** [comment]
Sure here you go

[lan-mouse-left-donkler.log](https://github.com/user-attachments/files/17277641/lan-mouse-left-donkler.log)
[lan-mouse-right-donkinator.log](https://github.com/user-attachments/files/17277644/lan-mouse-right-donkinator.log)

**Comment by serdonke** [comment]
Ah ok... I think it is more of a network issue, I connected to my laptop (`left`) via `right` using ssh and it was slow as hell...which is strange given it is a local connection.

then I pinged `left` and those ping values are..., welp seems like a network issue, thank you for your patience @feschber , I will update after I fix this, I guess you may decide if you wish to close the issue.

```
  data ping 192.168.1.6
PING 192.168.1.6 (192.168.1.6) 56(84) bytes of data.
64 bytes from 192.168.1.6: icmp_seq=1 ttl=64 time=3583 ms
64 bytes from 192.168.1.6: icmp_seq=2 ttl=64 time=2572 ms
64 bytes from 192.168.1.6: icmp_seq=3 ttl=64 time=1548 ms
64 bytes from 192.168.1.6: icmp_seq=4 ttl=64 time=525 ms
64 bytes from 192.168.1.6: icmp_seq=5 ttl=64 time=903 ms
64 bytes from 192.168.1.6: icmp_seq=6 ttl=64 time=6.54 ms
64 bytes from 192.168.1.6: icmp_seq=7 ttl=64 time=9300 ms
64 bytes from 192.168.1.6: icmp_seq=8 ttl=64 time=8269 ms
64 bytes from 192.168.1.6: icmp_seq=9 ttl=64 time=7245 ms
64 bytes from 192.168.1.6: icmp_seq=10 ttl=64 time=6221 ms
64 bytes from 192.168.1.6: icmp_seq=11 ttl=64 time=5197 ms
64 bytes from 192.168.1.6: icmp_seq=12 ttl=64 time=4173 ms
64 bytes from 192.168.1.6: icmp_seq=13 ttl=64 time=3149 ms
64 bytes from 192.168.1.6: icmp_seq=14 ttl=64 time=2125 ms
64 bytes from 192.168.1.6: icmp_seq=15 ttl=64 time=1101 ms
64 bytes from 192.168.1.6: icmp_seq=16 ttl=64 time=77.3 ms
64 bytes from 192.168.1.6: icmp_seq=17 ttl=64 time=9320 ms
64 bytes from 192.168.1.6: icmp_seq=18 ttl=64 time=8273 ms
64 bytes from 192.168.1.6: icmp_seq=19 ttl=64 time=7249 ms
64 bytes from 192.168.1.6: icmp_seq=20 ttl=64 time=6225 ms
64 bytes from 192.168.1.6: icmp_seq=21 ttl=64 time=5201 ms
64 bytes from 192.168.1.6: icmp_seq=22 ttl=64 time=4177 ms
64 bytes from 192.168.1.6: icmp_seq=23 ttl=64 time=3153 ms
64 bytes from 192.168.1.6: icmp_seq=24 ttl=64 time=2129 ms
64 bytes from 192.168.1.6: icmp_seq=25 ttl=64 time=1105 ms
64 bytes from 192.168.1.6: icmp_seq=26 ttl=64 time=81.6 ms
64 bytes from 192.168.1.6: icmp_seq=27 ttl=64 time=4199 ms
64 bytes from 192.168.1.6: icmp_seq=28 ttl=64 time=3152 ms
64 bytes from 192.168.1.6: icmp_seq=29 ttl=64 time=2128 ms
64 bytes from 192.168.1.6: icmp_seq=30 ttl=64 time=1104 ms
64 bytes from 192.168.1.6: icmp_seq=31 ttl=64 time=80.7 ms
64 bytes from 192.168.1.6: icmp_seq=32 ttl=64 time=4200 ms
64 bytes from 192.168.1.6: icmp_seq=33 ttl=64 time=3153 ms
64 bytes from 192.168.1.6: icmp_seq=34 ttl=64 time=2129 ms
64 bytes from 192.168.1.6: icmp_seq=35 ttl=64 time=1106 ms
64 bytes from 192.168.1.6: icmp_seq=36 ttl=64 time=81.6 ms
```
