### ISSUE TITLE
"device not responding" when typing (keyboard) from Linux to MacOS

### ISSUE THREAD

**Issue by PedroHLC** [feschber/lan-mouse#220]
On 7496015d8d36fe58cc2f915991e90d1acc1aa9cd, when typing from Linux/wlroots (capture) to MacOS (emulates), if I enter two keys quickly (same second) some random key gets stuck instead, output on MacOS side starts repeating the following:
```
WARN  lan_mouse::server::ping_task] client not responding, releasing pointer!
WARN  lan_mouse::server::ping_task] device not responding, releasing keys!
WARN  lan_mouse::server::ping_task] device not responding, releasing keys!
WARN  lan_mouse::server::ping_task] device not responding, releasing keys!
WARN  lan_mouse::server::ping_task] device not responding, releasing keys!
WARN  lan_mouse::server::ping_task] device not responding, releasing keys!
WARN  lan_mouse::server::ping_task] device not responding, releasing keys!
WARN  lan_mouse::server::ping_task] device not responding, releasing keys!
WARN  lan_mouse::server::ping_task] device not responding, releasing keys!
WARN  lan_mouse::server::network_task] udp send failed: network error: `No route to host (os error 65)`
WARN  lan_mouse::server::ping_task] device not responding, releasing keys!
WARN  lan_mouse::server::network_task] udp send failed: network error: `Host is down (os error 64)`
WARN  lan_mouse::server::ping_task] device not responding, releasing keys!
WARN  lan_mouse::server::network_task] udp send failed: network error: `Host is down (os error 64)`
WARN  lan_mouse::server::ping_task] device not responding, releasing keys!
WARN  lan_mouse::server::network_task] udp send failed: network error: `Host is down (os error 64)`
WARN  lan_mouse::server::ping_task] device not responding, releasing keys!
WARN  lan_mouse::server::network_task] udp send failed: network error: `Host is down (os error 64)`
WARN  lan_mouse::server::ping_task] device not responding, releasing keys!
WARN  lan_mouse::server::network_task] udp send failed: network error: `Host is down (os error 64)`
WARN  lan_mouse::server::ping_task] device not responding, releasing keys!
WARN  lan_mouse::server::network_task] udp send failed: network error: `Host is down (os error 64)`
WARN  lan_mouse::server::ping_task] device not responding, releasing keys!
WARN  lan_mouse::server::network_task] udp send failed: network error: `Host is down (os error 64)`
WARN  lan_mouse::server::ping_task] device not responding, releasing keys!
WARN  lan_mouse::server::network_task] udp send failed: network error: `Host is down (os error 64)`
WARN  lan_mouse::server::ping_task] device not responding, releasing keys!
WARN  lan_mouse::server::network_task] udp send failed: network error: `Host is down (os error 64)`
WARN  lan_mouse::server::ping_task] device not responding, releasing keys!
WARN  lan_mouse::server::network_task] udp send failed: network error: `Host is down (os error 64)`
WARN  lan_mouse::server::ping_task] device not responding, releasing keys!
WARN  lan_mouse::server::network_task] udp send failed: network error: `Host is down (os error 64)`
WARN  lan_mouse::server::ping_task] device not responding, releasing keys!
WARN  lan_mouse::server::network_task] udp send failed: network error: `Host is down (os error 64)`
WARN  lan_mouse::server::ping_task] device not responding, releasing keys!
WARN  lan_mouse::server::network_task] udp send failed: network error: `Host is down (os error 64)`
```
It only stops when I `kill -KILL` it, `Ctrl+C` shows `INFO  lan_mouse::server] terminating service` but never exists.

The same does not happen if I invert the actors (MacOS captures, wlroots emulates), and I can keep the connection going for hours if I type very slowly.

I always need to restart it on the MacOS side.

---

On top of that, good work overall with this app, been using it sporadically since February!

NOTE: With the macOS, I only tested this commit and commit 9248007986ade8a0690ce37bccbf463927d2df6b. When I tried `9248007` in the macOS, the other machines couldn't connect to it at all, and I skipped directly to the last commit, this last commit connects, but I need to `ssh machine -- killall -KILL lan-mouse` when I forget about this issue.

**Comment by PedroHLC** [comment]
I'm unable to reproduce this in the latest commit.

**Comment by feschber** [comment]
Sorry I did not respond earlier. The whole response tracking / ping logic has changed with the encryption stuff, hopefully it's working better now ;)

**Comment by mechanicpanic** [comment]
I have the same issue right now (installed 0.10 with cargo on both sides), Hyprland -> MacOS. Anything I could try? Because otherwise I love the app, using two machines is super useful for me - thanks!

**Comment by grodius** [comment]
> Sorry I did not respond earlier. The whole response tracking / ping logic has changed with the encryption stuff, hopefully it's working better now ;)

I am having an issue where the ping_task is failing, using hyprland -> macos like the above user. It works perfectly until the task fails then I have to kill the process on the mac to release the server's keyboard/mouse

**Comment by feschber** [comment]
> > Sorry I did not respond earlier. The whole response tracking / ping logic has changed with the encryption stuff, hopefully it's working better now ;)
> 
> I am having an issue where the ping_task is failing, using hyprland -> macos like the above user. It works perfectly until the task fails then I have to kill the process on the mac to release the server's keyboard/mouse

It would be very helpful, if you could provide the logs from when this happens

**Comment by grodius** [comment]
> > > Sorry I did not respond earlier. The whole response tracking / ping logic has changed with the encryption stuff, hopefully it's working better now ;)
> > 
> > 
> > I am having an issue where the ping_task is failing, using hyprland -> macos like the above user. It works perfectly until the task fails then I have to kill the process on the mac to release the server's keyboard/mouse
> 
> It would be very helpful, if you could provide the logs from when this happens

`

[lan-mouse-error.log](https://github.com/user-attachments/files/19354809/lan-mouse-error.log)

`

sorry about that - here you go

**Comment by grodius** [comment]
for some reason the fingerprint

> > > Sorry I did not respond earlier. The whole response tracking / ping logic has changed with the encryption stuff, hopefully it's working better now ;)
> > 
> > 
> > I am having an issue where the ping_task is failing, using hyprland -> macos like the above user. It works perfectly until the task fails then I have to kill the process on the mac to release the server's keyboard/mouse
> 
> It would be very helpful, if you could provide the logs from when this happens

something I notice, is i've never seen anything involving fingerprint in either client's UI, should I?

and also - are both machines supposed to be "clients"?

**Comment by feschber** [comment]
The fingerprint UI is going to come with version 0.11 soon™. Technically both machines are servers in <= 0.10 but this is now also going to change in that the controlling machine is now a client.

**Comment by grodius** [comment]
> The fingerprint UI is going to come with version 0.11 soon™. Technically both machines are servers in <= 0.10 but this is now also going to change in that the controlling machine is now a client.

ok.. thought maybe a misconfig of both declaring each other as "clients" could be forcing some loop and breaking the ping...

i hate to push a generous and talented dev into user support... but any idea what is going on with my set up? I posted the trace above too big to paste. 

my configs:

**hyprland machine (keyboard/mouse)**
`# example configuration

# configure release bind
release_bind = [ "KeyA", "KeyS", "KeyD", "KeyF" ]

# optional port (defaults to 4242)
port = 4242
# # optional frontend -> defaults to gtk if available
# # possible values are "cli" and "gtk"
frontend = "gtk"

# define a client on the right side with host name "iridium"
[right]
# hostname
hostname = "mbp.lan"
# activate this client immediately when lan-mouse is started
activate_on_startup = true
# optional list of (known) ip addresses
ips = ["192.168.8.186", "192.168.8.187"]

# define a client on the left side with IP address 192.168.178.189
[left]
# The hostname is optional: When no hostname is specified,
# at least one ip address needs to be specified.
#hostname = "gn0"
# ips for ethernet and wifi
#ips = ["192.168.8.96"]
# optional port
#port = 4242`

**mac ("client")**
`
port = 4242
frontend = "cli"


[[clients]]
position = "left"
hostname = "gn0.lan"
ips = ["192.168.9.96"]
activate_on_startup = true`
