### ISSUE TITLE
Host peripherals that move to Windows from Linux cannot move back

### ISSUE THREAD

**Issue by MulverineX** [feschber/lan-mouse#46]
The magic edge appears to be broken on Windows, to work around it the connection must be deactivated.

Environments:
Sending
> Latest KDE Plasma on Arch Linux
> lan-mouse@010db79
> ```toml
> frontend = "cli"
> 
> [left]
> host_name = "zhulong"
> ips = ["192.168.77.74"]
> port = 4242
> ```
> `cargo run --release --no-default-features --features wayland,xdg_desktop_portal,x11`

Receiving
> Latest Windows 11
> lan-mouse@v0.4.0
> ```toml
> frontend = "cli"
> 
> [right]
> host_name = "haixiong"
> ips = ["192.168.77.117"]
> port = 4242
> ```

**Comment by feschber** [comment]
Yes, input capture is not yet implemented in Windows so this is expected. For now, you can release the mouse by pressing Ctrl+alt+shift+super (on the Linux machine)

**Comment by MulverineX** [comment]
I'm not sure I understand, the input is happening on Linux

**Comment by MulverineX** [comment]
This appears to persist in 0.5.0

**Comment by beyertom** [comment]
I didnt read anything in the readme or the commit logs, but for me the magic-edge on windows works now with v0.5.1 (Server wlroots / Client Windows).

Thank you very much, awesome project!

**Comment by feschber** [comment]
> I didnt read anything in the readme or the commit logs, but for me the magic-edge on windows works now with v0.5.1 (Server wlroots / Client Windows).
> 
> Thank you very much, awesome project!

Are you by any chance using Hyprland on the server side?

**Comment by beyertom** [comment]
yes i do

**Comment by beyertom** [comment]
what a conicidence, i actually added a second screen to my server since i tested lan-mouse the last time.

The resolution of windows is not the same as the main monitor of the Server (the one "right" of Windows).

 I am not complaining, though. It works exactly how I wanted it to be. :-)

**Comment by feschber** [comment]
Whatever works for you I guess!
I will see that I can add proper support for at least detecting when the screen is exited on the windows side soon.

**Comment by beyertom** [comment]
yesterday i upgraded to Hyprland 0.35.0 and now unfortuneately its not working anymore

**Comment by feschber** [comment]
> yesterday i upgraded to Hyprland 0.35.0 and now unfortuneately its not working anymore.
> 
> The client screen is on the left, and i can move the mouse there only more to the left. unti iam at the very left edge of the screen

Jup - See readme. There was a regression.

**Comment by fecet** [comment]
Problem persist by using hyprland https://github.com/hyprwm/Hyprland/commit/a01949dd286ba67f8026aeec38b44b61e20be412

**Comment by feschber** [comment]
> Problem persist by using hyprland https://github.com/hyprwm/Hyprland/commit/a01949dd286ba67f8026aeec38b44b61e20be412

Windows input capture support is next on the list ;)

**Comment by MulverineX** [comment]
uhhh, @feschber this isn't working afaict

**Comment by feschber** [comment]
> uhhh, @feschber this still isn't working afaict. I'm using the 0.7.3 release. I'm guessing that https://github.com/feschber/lan-mouse/pull/99 broke it

What exactly is not working? Did you get the latest pre-release binary and restart lan-mouse?

**Comment by MulverineX** [comment]
@feschber I've tried 0.7.3 & 0.5.1, neither let me move the cursor back. Also, it appears there was a regression on input in Windows on both versions, where every mouse click is duplicated **very** quickly, causing bugs in several applications and highlighting a whole word in text editors.

**Comment by feschber** [comment]
@MulverineX Please try the pre release. It does not show all changes since 0.7.3 in the release notes until I update to 0.8

**Comment by MulverineX** [comment]
Aha! Yep, I realized this after I sent that message, there hasn't been a build for a while. I'm on the 0.8 pre-release now, the duplicated mouse clicks are fixed, but the "edge" of my screen is being calculated incorrectly. I have a 2560x1440p display, but it appears to think that my screen on Windows ends at 1920 and jumps over to linux early.

**Comment by MulverineX** [comment]
@feschber also, scrolling is way slower on the client device, and using the Ctrl+Shift+Alt+Super fallback for releasing the cursor causes those keys to be locked again in the client device.

**Comment by MulverineX** [comment]
Would display Scale effect it?
![image](https://github.com/feschber/lan-mouse/assets/12068027/03c2f6f1-f869-4121-bf25-dc44671c7ab7)

Also, I have a bit of a weird setup, My windows machine is a laptop that traditionally has a 1080p screen attached, but has since been removed. Perhaps the API you're using is giving you details for that non-existent display, rather than the external monitor my mouse is actually on?

**Comment by feschber** [comment]
> @feschber also, scrolling is way slower on the client device, and using the Ctrl+Shift+Alt+Super fallback for releasing the cursor causes those keys to be locked again in the client device.

This is intentional (sort of, will need to fix this of course) and one reason I have not made a new release yet.

**Comment by feschber** [comment]
> Would display Scale effect it?
> ![image](https://github.com/feschber/lan-mouse/assets/12068027/03c2f6f1-f869-4121-bf25-dc44671c7ab7)
> 
> Also, I have a bit of a weird setup, My windows machine is a laptop that traditionally has a 1080p screen attached, but has since been removed. Perhaps the API you're using is giving you details for that non-existent display, rather than the external monitor my mouse is actually on?

Could you run it with $env:LAN_MOUSE_LOG_LEVEL='debug' and paste the output? That should show what displays are detected. And scale is something I have not tested so yeah that could be an issue.

**Comment by feschber** [comment]
full command should be
```powershell
$env:LAN_MOUSE_LOG_LEVEL='debug'; lan-mouse
```
(powershell)

**Comment by MulverineX** [comment]
Forgot to test this last night, will test later today

**Comment by MulverineX** [comment]
@feschber alright here you go.
[Windows client debug log](https://pastebin.com/tqDFNqMr)
[Arch Linux server debug log](https://pastebin.com/ebyTXaaG)

**Comment by MulverineX** [comment]
Alright I tried changing display scales while lan-mouse was not running. Changing the linux side to 100% did nothing, however, changing windows to 100% solved the problem.

**Comment by feschber** [comment]
There is another issue on windows - DNS resolution is extremely slow: https://github.com/hickory-dns/hickory-dns/issues/1968

In your logfile on the windows side, it's still trying to resolve the host (this can take like 30 seconds).
I'm in the process of adding this information to the UI.

I will test how exactly scaling effects things, thank you for catching that.

**Comment by feschber** [comment]
> Also, it appears there was a regression on remote input in Windows on both versions, where every mouse click is duplicated **very** quickly, causing bugs in several applications and highlighting a whole word in text editors, curiously Windows Explorer is not effected.

Could #91 have been the issue? Did you test a recent version?

**Comment by MulverineX** [comment]
> I'm on the 0.8 pre-release now, the duplicated mouse clicks are fixed
That's no longer happening

**Comment by feschber** [comment]
> > I'm on the 0.8 pre-release now, the duplicated mouse clicks are fixed
> 
> That's no longer happening

Ah I missed that part. I assume it must have been that issue then.

**Comment by MulverineX** [comment]
@feschber I think I found the problem, https://stackoverflow.com/a/26097858

> Your program does not declare itself to be high dpi aware. And so it is subject to a compatibility mode known as DPI virtualization. The system will supply your program with fake screen dimensions and coordinates, and then scale your program's display to the true dimensions.
> ...
> If you wish to avoid DPI virtualization, and have your program obtain true screen dimensions, then you should mark your program as being high DPI aware. This is best done with the high DPI aware application manifest.
```xml
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0" 
    xmlns:asmv3="urn:schemas-microsoft-com:asm.v3" >
  <asmv3:application>
  <asmv3:windowsSettings 
      xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">
    <dpiAware>true</dpiAware>
  </asmv3:windowsSettings>
  </asmv3:application>
</assembly>
```

**Comment by feschber** [comment]
Imo it's probably best to not be DPI aware and rather retrieve the actual display resolution via `EnumDisplaySettings`.
This way I dont have to rely on an application manifest (which currently does not exist)

**Comment by MulverineX** [comment]
Did some digging, this appears to be the method most are using to add a manifest to their Rust binaries https://github.com/nabijaczleweli/rust-embed-resource

**Comment by feschber** [comment]
could you confirm that the latest commit works?

**Comment by MulverineX** [comment]
@feschber It works perfectly! Thank you so much! If my situation was reversed though I would still have an issue, because Linux scaling isn't being taken into account either.

**Comment by feschber** [comment]
@MulverineX  are you sure about that? Because the scaling does not have any influence on the window position or size in wayland (layer-shell only wants to know on what edge to display the window).

You can verify the position of the "entry zones" via
```
export LM_DEBUG_LAYER_SHELL=1
lan-mouse
```

(assuming you are still using KDE)

**Comment by MulverineX** [comment]
Will look into this for ya later today

**Comment by MulverineX** [comment]
finally got around to testing this, its not an issue

**Comment by feschber** [comment]
Thanks for testing, appreciate it!

**Comment by MulverineX** [comment]
@feschber looks like there was another regression unfortunately. Games and other applications that capture the cursor aren't being handled correctly anymore. Moving to the right will bring the mouse offscreen, when it's supposed to be locked in.
