### ISSUE TITLE
Holding keys doesn't work

### ISSUE THREAD

**Issue by MulverineX** [feschber/lan-mouse#47]
Reproduce:
1. Move peripherals to client device
2. Press and hold any key

Expected: the key fires on the client once, then after a second it fires every 100ms

Actual: the key fires once and only once, pretty annoying for backspace.

It appears that KeyUp is being fired correctly, so my previous assertion that its a problem for games was incorrect.

**Comment by feschber** [comment]
What devices are you using on the sending / receiving end?

**Comment by MulverineX** [comment]
Same as #46

**Comment by feschber** [comment]
Okay so this is a Windows specific problem. The Windows Backend needs a bit of work.
