### ISSUE TITLE
Several keys are bound to the wrong keycodes on receiving clients

### ISSUE THREAD

**Issue by MulverineX** [feschber/lan-mouse#48]
May just be a Windows issue. Can't test.

Media Skip - `h`
Media Play/Pause - `j`
Media Previous - `k` (ironically the non-global hotkey for play/pause on YouTube)
Left - F18 / code 129
Up - F16 / code 127
Down - F21 / code 132
Right - F19 / code 130
Volume Up - IntlRo / 193
Volume Down - Lang1 / 255
Windows/Super/Meta - IntlYen / 255 (weird how its the same code)

Same environment as #46

**Comment by feschber** [comment]
I'm aware of this. Keycode translation is next on my list :). Linux and Windows are different.
See #16

**Comment by feschber** [comment]
@MulverineX should be working now! Tell me if some keys aren't mapped correctly.

**Comment by MulverineX** [comment]
Yep its working great now, thank you!!
