### ISSUE TITLE
How to install it in Linux and Windows? Any binary packages?

### ISSUE THREAD

**Issue by sgon00** [feschber/lan-mouse#67]
Thanks a lot for the project. But by reading the [README.md](https://github.com/feschber/lan-mouse/blob/main/README.md), I can only see how to build and run, but I am confused how to install it without building. Do I have to build it or are there any avaliable binary packages?

**Comment by sgon00** [comment]
@feschber thanks a lot for the reply. I did see the release section, but I am not sure if those files can be installed and ran directly without installing dependencies or not. Because README.md does NOT really make this clear. Do I still need to install libadwaita-1-dev etc. in ubuntu and follow [gtk-rs.org](https://gtk-rs.org/gtk4-rs/stable/latest/book/installation_windows.html) instructions in windows?

**Comment by sgon00** [comment]
@feschber I just tried the binary files in Ubuntu 23.10 and Windows 11. Apps can be launched successfully in both platforms. But when I click the "Add" button in Ubuntu, nothing happened. In windows, the "Add" button works. I am not sure if I did anything wrong because I have no ideas how to use it. I want to use my Ubuntu's mouse/keyboard (as server). Thus I think I need to add clients in Ubuntu, but I can not do that. Add button doesn't do anything.

**Comment by feschber** [comment]
Can you run it from the Terminal on the Ubuntu machine and show the output here?

Also please be aware that input capture does not work yet on Gnome Wayland so you will have to wait for that until this setup is usable.

I'm hoping to get it working in the next couple of weeks.

**Comment by feschber** [comment]
![Screenshot from 2024-01-10 16-59-53](https://github.com/feschber/lan-mouse/assets/40996949/9d49ab20-6b5c-4b92-a2dd-8791f15fb5e4)

be aware you won't be able to add devices until confirming this allow remote interaction dialog

**Comment by sgon00** [comment]
@feschber 
I read `"The primary target is Wayland on Linux"` in README.md, so I thought wayland worked. I am running Gnome Wayland because Ubuntu 23.10 runs it by default. The reason why I try lan-mouse because barrier does NOT work in wayland. 

I think the output does not have anything intereseting beacuse I compared the output to Windows version, I don't see anything different. The following is the output:

```
$ ./lan-mouse 
[2024-01-10T15:43:29Z ERROR lan_mouse::config] /home/user/.config/lan-mouse/config.toml: No such file or directory (os error 2)
[2024-01-10T15:43:29Z WARN  lan_mouse::config] Continuing without config file ...
[2024-01-10T15:43:29Z ERROR lan_mouse::config] /home/user/.config/lan-mouse/config.toml: No such file or directory (os error 2)
[2024-01-10T15:43:29Z WARN  lan_mouse::config] Continuing without config file ...
[2024-01-10T15:43:29Z INFO  lan_mouse] Press Ctrl+Alt+Shift+Super to release the mouse
[2024-01-10T15:43:29Z INFO  lan_mouse::consumer] wayland backend not available: the requested global was not found in the registry
[2024-01-10T15:43:29Z INFO  lan_mouse::producer] libei event producer not available: not implemented
[2024-01-10T15:43:29Z INFO  lan_mouse::producer] layer_shell event producer not available: zwlr_layer_shell_v1 >= v3 not supported - required to display a surface at the edge of the screen
[2024-01-10T15:43:29Z INFO  lan_mouse::producer] x11 event producer not available: not implemented
[2024-01-10T15:43:29Z ERROR lan_mouse::producer] falling back to dummy event producer
```

**Comment by feschber** [comment]
Wayland works but only on KDE and wlroots compositors so far. (This project is kind of in an early state still).

Did you see the mentioned dialog window appear?

Also be aware that Barrier is no longer maintained and instead the maintainers of barrier are now working on input-leap, which I thing recently got support for wayland.

**Comment by sgon00** [comment]
@feschber Thanks a lot for your help. I can "Add" clients now in Ubuntu. But It seems it doesn't work. I can not move cursor to my windows. I don't see any useful outputs. Maybe it's just because gnome wayland does not work.

I knew input-leap, but it doesn't provide binary installers officially. I am lazy to compile. So I don't plan to use it.

I found rkvm, it's written in rust too. It says it doesn't care of X, Wayland etc.. But it doesn't support windows. 

Anyway, I think I will simply give up KVM apps for now. Too much time for today. Since release page does provide binary packages, I will mark this issue as closed. Thank you very much.

**Comment by sgon00** [comment]
Cool and yeah, gnome wayland support and encryption are the features I am looking for. Thank you very much. :smile:

**Comment by feschber** [comment]
still some rough edges but GNOME works now :)
