### ISSUE TITLE
AUR Repository package

### ISSUE THREAD

**Issue by CupricReki** [feschber/lan-mouse#73]
I created the lan-mouse package in the aur. Please review and let me know your thoughts. I've never worked with cargo and this is my first submission to the AUR. 

https://aur.archlinux.org/packages/lan-mouse-git

I'm waiting for #72 before I add .desktop support. I'll add a service file for systemd once #70 and the daemon issues get sorted out. 

AUR package for bin is forthcoming.

**Comment by feschber** [comment]
First of all: Thank you for your work!

I took a look and have nothing to complain.

One thing to note is that `/usr/share/pixmaps` is deprecated.
You should probably move the icon to `/usr/share/icons/hicolor/scalable/apps/de.feschber.LanMouse.svg` now.

I also fixed the Icon Name and App Id such that it should now be correctly displayed:
https://github.com/feschber/lan-mouse/commit/13597b358733e2f0673f0b6d0d9790a024af12c4

**Comment by feschber** [comment]
And regarding the systemd service, maybe you can share some ideas, @alison-solsoft
( https://github.com/feschber/lan-mouse/issues/68#issuecomment-1888382031)

**Comment by CupricReki** [comment]
Thanks for the feedback and the updates. The AUR lan-mouse-git package has been updated.

**Comment by alison-solsoft** [comment]
Coincidentally, I was going to work on an AUR package myself once #70 was resolved, so thanks for taking it on already @CupricReki!

@feschber I have some thoughts relevant to running lan-mouse as a system daemon, but they are things that would need to be handled by packagers in general. I'll comment on the issue that Cupric created specific to the creation of a systemd unit (#76)

**Comment by feschber** [comment]
FYI @CupricReki: Adding me in the AUR worked, thanks!

**Comment by CupricReki** [comment]
Should I add an an example config to the package? Seems like the the correct location would be `/etc/lan-mouse/config.toml`.

**Comment by alison-solsoft** [comment]
An example config would be a good thing to include in the package. I would use ```/etc/lan-mouse/examples/config.toml``` to avoid potential conflicts if / when a package update modifies the example config, but that would only be an issue if it becomes possible to run lan-mouse as a system service, and ```/etc/lan-mouse/config.toml``` is used for configuration.

**Comment by feschber** [comment]
I added the installation instructions to the README.md

Will close this issue for now

**Comment by feschber** [comment]
closing
