### ISSUE TITLE
Re-lauching gtk frontend after starting as deamon shows incorrect connection state

### ISSUE THREAD

**Issue by CupricReki** [feschber/lan-mouse#75]
Position of slider in GUI shows incorrectly. It should be to the right, since the connection is active. 

![image](https://github.com/feschber/lan-mouse/assets/6509200/49d97cd8-050c-40ce-aa54-caf6c4247bf5)

## Steps to reproduce
1. Start as daemon `lan-mouse -d` 
2. Launch GUI `lan-mouse`
3. Enable connection
4. Close GUI
5. Re-Launch GUI `lan-mouse`

**Comment by feschber** [comment]
Working on it ;) #70
