### ISSUE TITLE
Run as service via systemd 

### ISSUE THREAD

**Issue by CupricReki** [feschber/lan-mouse#76]
Here is an example service file. Connection still needs to be activated via GUI until #70 is sorted.

```
/usr/lib/systemd/user/lan-mouse.service
```

```
[Unit]
Description=Mouse & keyboard sharing via LAN
Wants=network-pre.target
After=network-pre.target NetworkManager.service systemd-resolved.service

[Service]
ExecStart=/usr/bin/lan-mouse -d
Restart=on-failure

[Install]
WantedBy=multi-user.target
```
Start now and on boot
```
systemclt --user daemon-reload
systemctl --user enable --now lan-mouse.service
```

**Comment by alison-solsoft** [comment]
This lines up with what I had created on my own end for a user daemon unit. Do we also want to consider the option of a system daemon unit, which would require both a global config path (/etc/lan-mouse/config.toml) and dedicated daemon user (lanmouse)?

I have a specific use case that will require either enabling lingering on my user session on one of my systems, or running the service under the system daemon. Using session lingering isn't a terrible solution, but it isn't obvious to less-experienced Linux users that lingering is even an option.

**Comment by feschber** [comment]
A system service will not work because lan-mouse does not wait for a session to come online and simply falls back to the dummy backend. I would need to implement a way to wait for a session first. (Using systemd?)

I have been thinking about how that could be done but it will definitely take some effort. Maybe something similar to how rkvm works.

**Comment by alison-solsoft** [comment]
Upon further review, I have an additional thought:

Is there a reason you used "network-pre.target <network services>" rather than simply "network.target"? I think it would be better to avoid tying service ordering to specific network management services, as that can potentially lead to issues for users of other network daemons (e.g. netctl in my case). If it's a startup delay concern, I don't think ordering against network.target would drastically increase startup times, at least not as much as network-online.target.

**Comment by feschber** [comment]
> Upon further review, I have an additional thought:
> 
> Is there a reason you used "network-pre.target " rather than simply "network.target"? I think it would be better to avoid tying service ordering to specific network management services, as that can potentially lead to issues for users of other network daemons (e.g. netctl in my case). If it's a startup delay concern, I don't think ordering against network.target would drastically increase startup times, at least not as much as network-online.target.

Network should actually not be necessary at all, as lan-mouse is connection less and simply starts working as soon as a network is connected. It should however be ensured that a graphical session is running. I'm guessing `graphical-session.target` would be the right choice. There may still be a race condition between dbus an the lan-mouse service. I will need to look into that.

**Comment by feschber** [comment]
Same goes for DNS. We probably should not assume that systemd-resolved is used either way.

**Comment by CupricReki** [comment]
All good reasoning. Makes sense to exclude all the Wants/After. It was mostly there based on the example I was using.

**Comment by feschber** [comment]
It should now be possible to automate everything. Tell me if you notice any bugs :) And so feel free to open a PR for the user service.

**Comment by CupricReki** [comment]
Great news! I'll give it a go this evening. Have you thought about adding a daemon option to the GUI and/or a tray icon?

**Comment by feschber** [comment]
My latest commit broke it again. Have to fix asap

**Comment by feschber** [comment]
```ini
[Unit]
Description=Mouse & keyboard sharing via LAN
After=graphical-session.target

[Service]
ExecStart=/usr/bin/lan-mouse --daemon
Restart=on-failure

[Install]
WantedBy=graphical-session.target
```

Did some testing my self. The above seems to work for me. `After=graphical-session.target` must be specified as `After`, if it were `Required` it does not work (because lan-mouse would start at the same time).

**Comment by feschber** [comment]
There was one final bug that prevented it from working (forgot to do an initial dns request ...)

**Comment by CupricReki** [comment]
Seems to be working well for me. Connections aren't started automatically yet. Is the [activate-on-startup](https://github.com/feschber/lan-mouse/tree/activate-on-startup) branch ready for testing? 

I'll add the service to the AUR once connections can be automatically started.

**Comment by feschber** [comment]
If you want, you could update the AUR packages @CupricReki

**Comment by CupricReki** [comment]
So I'm thinking, add the install the systemd but don't enable it.

**Comment by feschber** [comment]
Yeah, it should not be enabled by default. Especially since the Input Capture / Emulation popups show up every restart on e.g. Gnome Desktop.
