### ISSUE TITLE
Proxy software tun mode cause addr mismatch

### ISSUE THREAD

**Issue by ICE-GB** [feschber/lan-mouse#77]
When the request passes through the proxy software using tun mode, the source port will change, causing lan-mouse to ignore the request, is it possible to just determine if the ip is the same?

After I modified it like this it worked for me

```rust
c.active && c.client.addrs.iter().any(|&item| match_socket_addr(&item, &addr))
```

```
fn match_socket_addr(addr1: &SocketAddr, addr2: &SocketAddr) -> bool {
    addr1.ip() == addr2.ip()
}
```

**Comment by feschber** [comment]
Yes that would be possible. I have been thinking to do this to allow using it with NAT or similar setups like you described. Probably not the worst idea but debatable if this should be optional or not.

**Comment by feschber** [comment]
I think there is actually no downside to allowing incoming requests from arbitrary ports.

I've gone a bit further than what you proposed and replaced the socket_addrs  HashSet with ips completely.
See #78

You can try it out (prebuilt binaries are available @ https://github.com/feschber/lan-mouse/actions/runs/7544659639 if you want).

Will do some more testing to ensure its correct

**Comment by ICE-GB** [comment]
Thanks! I'll give it a try!
