### ISSUE TITLE
cursor bound to single screen

### ISSUE THREAD

**Issue by jpeeler** [feschber/lan-mouse#83]
With the merge of #81, I was able to test lan-mouse for the first time between a Linux server and MacOS client. I'm using multiple screens and see that when the mouse works on the remote client screen, it is not able to continue to the adjoining screens.

I was kind of hoping that the mouse would automatically release on the edge when traversing to go back to the server. Unsure if that's because of the above issue or if you have to press the release keys by design.

(Unrelated, but there is some keyboard weirdness with the server not passing through keystrokes that are already mapped for usage in the compositor. Will report that later in another issue.)

**Comment by feschber** [comment]
> (Unrelated, but there is some keyboard weirdness with the server not passing through keystrokes that are already mapped for usage in the compositor. Will report that later in another issue.)

What compositor are you using on the server side?

**Comment by jpeeler** [comment]
That restriction removal works, but then seems to let the mouse descend off the edge display forever.

I'm using hyprland. Would you like a separate issue made?

**Comment by feschber** [comment]
A yeah, Hyprland has some issues.
- It reports that shortcuts-inhibit is supported but its not actually implemented. This is probably what you are experiencing.
- The pointer-constraints implementation was broken recently in conjunction with layershell (I already reported that)
- The pointer constraints stop working when the cursor is moved on a second screen (it somehow moves even though its locked)

https://github.com/hyprwm/Hyprland/issues/4465
https://github.com/hyprwm/Hyprland/issues/4464

But there is nothing I can fix on my end.

**Comment by feschber** [comment]
Yes I have seen it but not hat the time to test until now.
Both are fixed :) And shortcuts inhibit also work. That's great news.

**Comment by Jacoby6000** [comment]
For the macos issue where the cursor is stuck on a single monitor, I have implemented a fix: #202
