### ISSUE TITLE
Feature request: configurable release shortcut

### ISSUE THREAD

**Issue by qdel** [feschber/lan-mouse#85]
Hello,

More a feature request. On windows, actually the shortcut ctrl+alt+shift+win shortcut is used by office 365 app and cannot be easily-user "unset".

The shortcut is actually sent on the remote before releasing the cursor.

2 ways:
- do not send the event to the remote
- allows the user to change the shortcut (as anyway, any shortcut we come up with, won't match a user.)

**Comment by feschber** [comment]
Yeah good idea, I was already planning to add this at some point

**Comment by feschber** [comment]
Planning to add something to the ui as well
