### ISSUE TITLE
Mouse gets stuck in gnome

### ISSUE THREAD

**Issue by bgreggsmith** [feschber/lan-mouse#86]
lan-mouse 0.5.1 on both machines. Primary machine using sway, secondary machine using gnome 45.3.

Pointer can enter gnome and control works just fine. It is however unable to leave gnome by moving the pointer, either from the primary PC's mouse, or the gnome machines' mouse.

**Comment by feschber** [comment]
Yeah that has to do with input capture. I need it in order to see when the cursor exits the screen.
It's almost ready but I'm currently blocked on an issue in ashpd.

You can release the mouse with Ctrl+alt+shift+win for now.
