### ISSUE TITLE
README update for Sway

### ISSUE THREAD

**Issue by ackstorm23** [feschber/lan-mouse#90]
FYI 

The Sway dev's ignored https://github.com/swaywm/sway/issues/7936 and proceeded to release Sway 1.9 anyways.  

This means the official package, not just the git repository, would encounter this break. I am proposing that the README should be updated to reflect that **only** sway version 1.8 or lower is supported.  (as reverting to the official package from git won't cause the break to go away)

**Comment by feschber** [comment]
You are right, I updated the description. Thanks!

**Comment by feschber** [comment]
@ackstorm23 I just tested sway version 1.9 from the Arch repositories and somehow this bug is not present?
Can you confirm?
